language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
script: yarn test && yarn storybook:export
deploy:
  skip_cleanup: true
  provider: surge
  project: build
  domain: react-observed.surge.sh
  on: master